name: Build image

on:
  push:
    paths-ignore:
      - '*.org'
      - '.github/**'

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5

    - uses: cachix/install-nix-action@a809471b5c7c913aa67bec8f459a11a0decc3fce # v31

    - run: nix build '.#image'

    - run: docker load < result

    - uses: docker/login-action@184bdaa0721073962dff0199f1fb9940f07167d1 # v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
      # if: ${{ github.ref == 'refs/heads/master' }}

    - name: Push image
      run: |
        IMAGE_ID=ghcr.io/${{ github.repository_owner }}/flake-no-path-action
        VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
        [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')
        # Use Docker `latest` tag convention
        [ "$VERSION" == "master" ] && VERSION=latest
        echo IMAGE_ID=$IMAGE_ID
        echo VERSION=$VERSION
        docker tag flake-no-path:latest $IMAGE_ID:$VERSION
        docker push $IMAGE_ID:$VERSION
      if: ${{ github.ref == 'refs/heads/master' }}
